language: go

go:
  - "1.10.x"
  - "1.11.x"

sudo: required

go_import_path: github.com/XiaoMi/soar

addons:
  apt:
   sources:
    - mysql-5.7-trusty
   packages:
    - mysql-client

services:
  - docker

before_install:
  - docker pull mysql
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

script:
  - make build
  - make docker
  - make cover
  - make test-cli
